paths:
  /api/products/:
    get:
      # Descripción de la operación GET
      summary: Todos los productos fueron obtenidos 
      tags:
        - Products
      # Tipo de respuesta
      responses:
        "200":
          description: Todos los productos fueron tomados correctamente 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          description: Hubo un problema con el servidor     

  /api/products/{productId}:
    put:
      summary: El producto ha sido actualizado
      tags:
        - Products
      parameters:
        - name: productId
          in: path
          required: true
          description: ID del producto a actualizar 
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/createUpdateProduct"
      # Tipo de respuesta
      responses:
        "200":
          description: Producto actualizado     
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateSuccess"
 

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: objectId
          description: id generated by database
        title:
          type: string
          description: Title by product
        category:
          type: string
          description: Category by product
        stock:
          type: number
          description: Stock by product
        price:
          type: number
          description: Price by product 
      example:
        _id: ObjectId("#536456vfd")
        title: rice
        category: clothe
        stock: 30
        price: 1000

    UpdateSuccess:
      type: object
      properties:
        status:
          type: string
        message:
          type: string  
      example:
        status: success
        message: producto actualizado

  requestBodies:
    createUpdateProduct:
      type: object
      properties:
        title:
          type: string
          description: Title by product
        category:
          type: string
          description: Category by product
        stock:
          type: number
          description: Stock by product
        price:
          type: number
          description: Price by product 
      example:
        _id: ObjectId("#536456vfd")
        title: rice
        category: clothe
        stock: 30
        price: 1000


